# Site settings
title: NodeGit
description: Asynchronous native Node bindings to libgit2
url: "http://nodegit.org" # the base hostname & protocol for your site
date_format: "ordinal"

# Build settings
markdown: kramdown
highlighter: pygments
